default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: amazon_copy_development

test:
  <<: *default
  database: amazon_copy_test

production:
  <<: *default
  database: amazon_copy_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
